import { CompanySector, Statement2 } from '@efex-services/client/types';
import { DateTime } from 'luxon';

export interface FormData {
  accountCurrency: string;
  accountNumber: string;
  accountType: string;
  addressLine: string;
  addressLine1: string;
  addressLine2: string;
  bankCode: string;
  bankName: string;
  bankStatement: File | undefined;
  birthDate: DateTime;
  certificateFile: File | undefined;
  citizenship: string;
  city: string;
  constitutionFile: File | undefined;
  countryOrigin: string;
  idFileBack: File | undefined;
  idFileFront: File | undefined;
  idNumber: string;
  idType: string;
  incorporation: DateTime;
  isBankStatementUploaded?: string;
  isCertificateUploaded?: string;
  isConstitutionUploaded?: string;
  isIdFileBackUploaded?: string;
  isIdFileFrontUploaded?: string;
  isLastStep: boolean;
  isResidenceUploaded?: string;
  isSatUploaded?: string;
  phoneNumber: string;
  postCode: string;
  residenceFile: File | undefined;
  routingNumber: string;
  satFile: File | undefined;
  state: string;
  taxId: string;
  website: string;
}

export interface FormDataFromPartial {
  accountCurrency: string;
  accountNumber: string;
  accountType: string;
  addressLine: string;
  addressLine1: string;
  addressLine2: string;
  bankCode: string;
  bankName: string;
  bankStatement?: File | undefined;
  birthDate: DateTime;
  certificateFile?: File | undefined;
  citizenship: string;
  city: string;
  constitutionFile?: File | undefined;
  idFileBack?: File | undefined;
  idFileFront?: File | undefined;
  idNumber: string;
  idType: string;
  incorporation: DateTime;
  isBankStatementUploaded?: string;
  isCertificateUploaded?: string;
  isConstitutionUploaded?: string;
  isIdFileBackUploaded?: string;
  isIdFileFrontUploaded?: string;
  isResidenceUploaded?: string;
  isSatUploaded?: string;
  phoneNumber: string;
  postCode: string;
  residenceFile?: File | undefined;
  routingNumber: string;
  satFile?: File | undefined;
  state: string;
  taxId: string;
  website: string;
  question1?: string;
  question2?: string;
  question3?: string;
  question4?: string;
  question5?: string;
  question6?: string;
  question7?: string;
  question8?: string;
  companySector?: CompanySector;
  statements?: Statement2[];
}
